modifying the frontend pipeline to inlcude checks to dev and branch protection check on main

diff --git a/.github/workflows/frontend-pipeline.yml b/.github/workflows/frontend-pipeline.yml
--- a/.github/workflows/frontend-pipeline.yml
+++ b/.github/workflows/frontend-pipeline.yml
@@ -4,16 +4,22 @@ on:
   push:
     branches:
       - main
-      - feature/front-end
+      - dev
   pull_request:
     branches:
       - main
-      - feature/front-end
+      - dev
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
+      - name: Branch protection checks
+        run: |
+          if [["${GITHUB_EVENT_NAME}" == "push" && "${GIHUB_REF}" == "refs/heads/main"]] ; then 
+            echo "Error : Direct pushes to main are not allowed. Please use a pull request ."
+            exit 1
+          fi
       - uses: actions/checkout@v4
       - name: Setup Node.js
         uses: actions/setup-node@v4
